config/routes.rb
Devloop::Application.routes.draw do
  resources :projects

  resources :versions

  resources :iterations

  resources :profiles

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :tasks

  root :to => "home#index"
end

app/models/profile.rb
class Profile
  include Mongoid::Document
  field :name, :type => String
  field :description, :type => String
  field :homepage, :type => String
  field :statusnet, :type => String
  field :gitorious, :type => String

  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :ok }
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.haml
= simple_form_for @profile do |form|

  -if @profile.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@profile.errors.count, "error")} prohibited this #{Profile.name.titleize} from being saved:"
      %ul
        - @profile.errors.full_messages.each do |msg|
          %li= msg  

  = form.input :name, :label => 'Name'
  = form.input :description, :label => 'Description'
  = form.input :homepage, :label => 'Homepage'
  = form.input :statusnet, :label => 'Statusnet'
  = form.input :gitorious, :label => 'Gitorious'

  .actions
    = form.button :submit

app/views/profiles/edit.html.haml
%h1 Editing profile

= render 'form'

= link_to 'Show', @profile
\|
= link_to 'Back', profiles_path

app/views/profiles/index.html.haml
%h1 Listing profiles

%table
  %tr
    %th Name
    %th Description
    %th Homepage
    %th Statusnet
    %th Gitorious
    %th
    %th
    %th

  - @profiles.each do |profile|
    %tr
      %td= profile.name
      %td= profile.description
      %td= profile.homepage
      %td= profile.statusnet
      %td= profile.gitorious
      %td= link_to 'Show', profile
      %td= link_to 'Edit', edit_profile_path(profile)
      %td= link_to 'Destroy', profile, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Profile', new_profile_path

app/views/profiles/new.html.haml
%h1 New profile

= render 'form'

= link_to 'Back', profiles_path

app/views/profiles/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @profile.name
%p
  %b Description:
  = @profile.description
%p
  %b Homepage:
  = @profile.homepage
%p
  %b Statusnet:
  = @profile.statusnet
%p
  %b Gitorious:
  = @profile.gitorious

= link_to 'Edit', edit_profile_path(@profile)
\|
= link_to 'Back', profiles_path